richardgirges/express-fileupload

- jslib/index.js
- package.json
Sorry I edited the js directly, but this should fix the this.data undefined.
When I tried to update the coffee file, I always got an unexpected indentation error when I ran `gulp coffee` after adding the following line `streamifier.createReadStream(buf).pipe(fstream)`
> Adding streamifier to make buffer into a stream - Closes #2

- lib/index.js
closes #14 
code is simple, it just checks that the buffer isn't empty, and returns void if so. otherwise, it returns the file object as expected.
> fix problem  in firefox with empty file upload

- lib/index.js
- req.files[fieldname] is an Object when no multiple files are sent in the same field.
- req.files[fieldname] is an Array of Objects when multiple files are sent for fieldname.
> Fix input fields with multiple enabled:

- lib/index.js
If a form has multiple fields with the same name only the value of the last field is returned in the form body. An array of values should be returned instead.
> Support arrays of fields (similar to busboy 'autoFields' option)

- lib/index.js
Using `buf = Buffer.concat([buf, data]);` on the data event copies the
data in a new larger buffer everytime. Instead, store the intermediate
small buffers in an array and concat only at the end.
Test with a 117MB file:
- before: 83.868 seconds
- after: 2.230 seconds
> improve performance for large files

- lib/index.js
Currently there is an unhandled error event when syntactically incorrect multipart data is sent by the client which causes node.js to crash. This PR adds basic handlers that allow the node server to live on.
```
events.js:160
throw er; // Unhandled 'error' event
^
Error: Part terminated early due to unexpected end of multipart data
at /var/www/web/server/node_modules/dicer/lib/Dicer.js:65:36
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```
> Add error handlers for parser errors

- lib/index.js
- test/fileLimitUploads.spec.js
When 'limit' event fires, it returns 413 (Payload Too Large). Let me know if there is anything you'd like to do differently :)
This should close #40
> Handle 'limit' event when file is over fileSize

- lib/fileFactory.js
- lib/index.js
- test/fileFactory.spec.js
- test/server.js
Hello there!
First of all: thank you for this project! Life & time saver.
I am using this middleware on several projects, and I have, on all of those project, the same problem:
> How can I correctly test my file uploading system?
The problem is:
I do not only upload files, but I also do some business transformation on them. As I try to keep everything as simple as possible: I just use your file object without decorator or anything else.
So, for the tests… it need many boilerplates or… a decorator…
This is why this pull request:
I would love to have a real FileObject / File or just a factory. I choose the factory option to keep this project also simple.
The steps are split on several commits. If you agree on the principe, I would like to talk about the last one: …
> Reusable file object

- lib/processMultipart.js
If we don't pass them then for example the `mv` function can't use the `createParentPath` property.
> [Bugfix] Pass options to File Factory

- lib/tempFileHandler.js
```
app.use(fileUpload({
useTempFiles: true,
tempFileDir: path.join(__dirname, 'upload_tmp')
}));
```
Error: ENOENT: no such file or directory, mkdir '/Users/linquan/xxx/node_modules/express-fileupload/lib/Users/linquan/xxx/upload_tmp'
so...
```
app.use(fileUpload({
useTempFiles: true,
tempFileDir: '/../../../../upload_tmp/'
}));
```
too ugly
> tempFileDir use absolute path.

- lib/fileFactory.js
- lib/memHandler.js
- lib/processMultipart.js
- lib/tempFileHandler.js
This PR moves memHandler in separate module and adds alpha version of file size to the module output.
That also should fix issue #118
> Move in memory handler to the separate module.

- lib/fileFactory.js
Moved 'mv' method local functions outside of the factory.
Added some comments.
Now in mv method we have one entry point for checking upload type(into memory or into a temporary file) instead of checking it two times for callback and promise cases.
Added check if callback is a function.
>  move mv method local funcs outside of the factory

- lib/processMultipart.js
- lib/utilities.js
- test/utilities.spec.js
Move save file names functionality to the separate functions parseFileName and parseFileNameExtension.
That made processMultipart.js code cleaner and also usefull for testing.
> add functions to parse file names

- lib/fileFactory.js
- lib/isEligibleRequest.js
- lib/processMultipart.js
- lib/utilities.js
- test/fileFactory.spec.js
- test/multipartUploads.spec.js
- test/utilities.spec.js
Make it lighter
Change multipart regexp to /^(multipart\/.+);(.*)$/i
Move empty files check to the fileFactory and add tests for it
> Anchancements for isEligibleRequest and fileFactory

- lib/utilities.js
- package-lock.json
- test/utilities.spec.js
When you use the `createParentPath` option, setting the path to a non-existent one with multiple levels makes this middleware fail because `fs.mkdirSync` throws an exception. This PR adds support for this case.
Thanks for this awesome package !
> Add support for recursive path creation in createParentPath

- lib/utilities.js
try to rename a (temporary) file before resorting to copyFile. fs.rename is much faster for large files and requires less empty disk space.
> if possible, use fs.rename for moveFile instead of copyFile

- README.md
- lib/processMultipart.js
- lib/utilities.js
- package.json
- test/utilities.spec.js
Cutting off huge file names by 255 characters.
BTRFS   255 bytes
exFAT   255 UTF-16 characters
ext2    255 bytes
ext3    255 bytes
ext3cow 255 bytes
ext4    255 bytes
FAT32   8.3 (255 UCS-2 code units with VFAT LFNs)
NTFS    255 characters
XFS     255 bytes
> Fixing vulnerability if file name length to big.

- lib/processMultipart.js
Previously upload timeout timer started only after first data chunk came.
If no data came at all timeout doesn't start so no cleanup will be performed in this case.
> fix: upload timer starts even no data has come.

- .travis.yml
- README.md
- lib/index.js
- package-lock.json
- package.json
* I've updated all dependencies to the latest versions.
* Moved `md5` out of `devDependencies` and into main `dependencies` since it's a required package
* Eliminated support in Travis CI for Node 6 and 7 (we need to make a major or minor release because of this)
* Added support for Node 11 and 12 in Travis CI
* Lastly, checked in results of `npm audit fix` in package-lock.json. 
NOTE: See my comments below, there is one test failing in Node 8 and 9.
NOTE 2: There are still various security alerts that we need to look into, I believe most of them are related to sub-dependencies of the `istanbul` package.
> Update all dev dependencies. Check in audit fix results

- lib/memHandler.js
- lib/processMultipart.js
- lib/tempFileHandler.js
#184 use promise to fix this bug
> fix:temp file write timing issue

- lib/memHandler.js
- lib/processMultipart.js
- lib/tempFileHandler.js
I did some optimization for PR #189 
- Add error handler to tempFileHandler writeStream
- Use 'Symbol' to prevent external access promises
> fix: add error handler to tempFileHandler

- lib/utilities.js
- test/utilities.spec.js
fix: Add empty file name check for parseFileName.
That fixes issue #187
> fix: Add empty file name check for parseFileName.

- lib/processMultipart.js
Follow up PR for #233
#233 seemed to exclude empty files from req.files but for temporary files, it still creates a writestream right after busboy triggers the `.on("file")` method, I did some research in hopes to find a flag for `fs.createWriteStream` to actually check and remove if the file is empty on the end but there's no such a thing.
And we are not able to **not** create a stream while we can't get the size info until the end, so the best thing we can do is follow the condition we have on `file.on('end')` and cleanup if `temporaryFiles` is enabled.
> Remove empty files

- lib/processMultipart.js
- The method "closeConnection" attempts to send a second response despite the parsed "limitHandler" function initially executing and sending its own custom response.
- This leads to the error - "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client".
- I have placed a condition for the "closeConnection" method to only be executed if a valid "limitHandler" function is NOT parsed into the options argument.
> (Fix) Stopped additional responses from being sent if a limit handler exists

- lib/processMultipart.js
Hi, I think that catching writePromise rejection on busboy _finish_ event seems too late, because it happens at  `dataHandler(data)` on busboy _data_ event and already in this point promise should have its reject callback in case of stream write errors. 
The best solution on writePromise rejection would be stop fetching rest of the request to not waste the bandwidth, similar like it is done in `closeConnection()` and then call `next(err)` error handler (not `next()` middleware`, but for now I don't get a well-functioning solution for that just this one.
> Unhandled promise rejection warning

- lib/utilities.js
This PR addresses failing tests in `test/fileFactory.spec.js`. These tests were failing because an `fsWriteStream` was emitting both an `error` event and a `close` event that caused the callback to fire twice.
However, this only happened when using a the callback interface to `file.mv`, as the promise interface would naturally "eat" the second event. In order to both fix the tests, and ensure that both promises and callbacks behave the same way to the user, this PR adjusts the behavior of the `promiseCallback` wrapper function to prevent duplicate callbacks.
> Have promiseCallback make callbacks and promises behave the same

- lib/processNested.js
- lib/utilities.js
- test/utilities.spec.js
Hi! Last weekend I found a low-impact prototype pollution in this module. It's only problematic in conjunction with certain antipatterns, but it is probably good to fix if possible. This PR makes a change that will fix it under normal usage, along with a few tests to verify that it remains fixed.
A couple of caveats, the first being that it will not address the problem if the caller manually sets `req.files` (or `req.body`) to an object. In this case, however, it is less trivial to determine what the correct behaviour should be, so I did not attempt to address it.
Secondly, this diff is a bit messy because VSCode decided to trim extra whitespace in a couple of places. If that's an issue, please let me know and I can manually revert those. 
Thanks!
Zach
> Fix prototype pollution in utilities.js

- lib/utilities.js
- test/utilities.spec.js
This PR fixes issue #342.
Unlike PR #343, this fix checks all of the not supported by the decodeURIComponent function characters.
uriDecodeFileName function now doesn't throw error when fileName param contains not supported by the decodeURIComponent characters.
Not supported characters will be removed from the result file name.
> Fix issue #342:URI malformed error.

- lib/processMultipart.js
- lib/tempFileHandler.js
- lib/utilities.js
- test/server.js
- test/utilities.spec.js
- Checks if `file` instance has `destroy` method to fix issue #259
- Rework utilities tests.
- Fix some typos and formatting.
- Remove deprecated fs.exists from test server.
- Add error logging for cleanDir function in test server.
> Fix issue #259 & some rework and formatting for utilities tests.

- lib/processMultipart.js
Do not run next after abortion on limit due unpiping busboy from request.
Check if headers has been sent in `closeConnection` function.
This is fixing #238
> Do not run next after abortion on limit

- lib/isEligibleRequest.js
- package-lock.json
- package.json
- test/isEligibleRequest.spec.js
Fix: Cannot read properties of undefined (reading 'includes') in lib/isEligibleRequest.js
Issue #364.
> Fix: Cannot read properties of undefined (reading 'includes').

- lib/processMultipart.js
- lib/uploadtimer.js
- package-lock.json
- package.json
- test/uploadtimer.spec.js
Use refresh for upload timer, instead of creating new timer each data chunk.
> Optimize upload timer.

- README.md
- lib/index.js
- lib/memHandler.js
- lib/tempFileHandler.js
- lib/utilities.js
- package.json
- test/utilities.spec.js
- hashAlgorithm key added to DEFAULT_OPTIONS
- hashAlgorithm key can be overriden by value given in options argument
- buildOptions function will ensure a default a hashAlgorithm exists, and throw an error if the provided option is not supported by the system.
- throws early error during app setup, rather than waiting until an upload is attempted
- memHandler and tempFileHandler use the hashAlgorithm option now
- Updated tests for buildOptions function in utilities.spec.js
ref: https://github.com/richardgirges/express-fileupload/issues/374
> Issue 374: Allow an option to choose the hashing algorithm

- lib/utilities.js
- package.json
- test/tempFile.spec.js
This PR adds process id to the temporary files name to fix file name collisions when running multiple node instances in the same environment.
See issue #384
> Add process id to the temp files name
