richardgirges/express-fileupload

lib/index.js
package-lock.json
package.json

Added md5 hash for each file upload. Based on the below issue: https://github.com/richardgirges/express-fileupload/issues/48

Added md5 checksum for each file upload

---

.gitignore
README.md
lib/index.js
test/fileLimitUploads.spec.js
test/server.js

Building on top of Haggus work, this add the option `abortOnLimit` (false by default as is less code). Also adds the `truncated` flag from Busboy on the returned structure.

Handle fileSize limit event with option

---

example/README.md
example/server.js

Hi! I recently came across this project. Huge fan.
One issue that I ran into was checking if no files had been uploaded. The docs recommend `if (!req.files)`. But as `req.files` has been intentionally left as an empty object to follow the same conventions of other middlewares, this if statement will never be true. The reasonable way seems to be to check if the object is empty. I've updated the docs to reflect this.
There's also some discussion about this in https://github.com/richardgirges/express-fileupload/issues/31
Thanks : )

Update docs to check for empty object

---

example/README.md

Typo in node.js

---

README.md
lib/fileFactory.js
lib/memHandler.js
lib/processMultipart.js
lib/tempFileHandler.js
package.json
test/fileFactory.spec.js
test/multipartUploads.spec.js
test/server.js
test/tempFile.spec.js

This PR add file size to the output object and md5 hash wich know calculates during uploading instead of returning md5 compute function.
It also adds support md5 for temp file upload mode.

Adds file size and md5 hash support

---

lib/fileFactory.js
lib/tempFileHandler.js
lib/utilities.js
package.json
test/fileFactory.spec.js
test/multipartUploads.spec.js
test/server.js
test/utilities.spec.js

This PR resolves issue #125 and adds more tests.

mv works across filesystems

---

lib/memHandler.js
lib/tempFileHandler.js
lib/utilities.js

That PR fixes issue with temporary files concurency because of not uniques file names.
See issue #129

Makes temp files names more unique

---

lib/processMultipart.js
lib/utilities.js
test/utilities.spec.js

Added buildOptions function to the utilities and used it in processMultipart to build busboy options.
That makes processMultipart lighter and cleaner.
Added additional tests for it, so it should increase a test coverage a bit.

Added buildOptions function

---

lib/memHandler.js
lib/tempFileHandler.js
lib/utilities.js
test/utilities.spec.js

This PR adds debugLog function and test for it.
Expected results:
- Cleaner code for upload handlers.
- Higher test coverage.

Add debugLog util function

---

lib/fileFactory.js
lib/memHandler.js
lib/processMultipart.js
lib/tempFileHandler.js
lib/utilities.js
test/utilities.spec.js

Add deleteFile, moveFile, buildFields functions to the utilities.
Make code ligher
Add some tests.

Make code lighter

---

example/README.md
example/server.js
lib/fileFactory.js
lib/index.js
lib/tempFileHandler.js

Add mode debug logging and  alse correct examples(see #142).

Add mode debug logging and correct examples

---

lib/memHandler.js
lib/processMultipart.js
lib/tempFileHandler.js
lib/uploadtimer.js
package.json
test/uploadtimer.spec.js

- Move upload timeout check into the separate module.
- Add check for zero uploadTimeout. #202

Update upload timeout check

---

lib/memHandler.js
lib/processMultipart.js
lib/tempFileHandler.js

Add upload complete flag to prevent write after stream end errors.
Issue #192

Add complete flag for upload handlers

---

lib/processMultipart.js
lib/tempFileHandler.js
lib/utilities.js

- Stop creating empty temp files for empty file fields
- Fix debugLog prefix
- Fix some jsdoc typos

Stop creating empty temp files for empty file fields

---

lib/processMultipart.js
lib/tempFileHandler.js

Destroy file stream in case of upload timeout.
Add debug loggin for temp file cleaning up insted throwing error, see #211

Destroy file stream in case of upload timeout.

---

README.md

Hi!
I added the timeout option to the documentation.
Relevant issue: #200

Add timeout option to README.MD

---

lib/fileFactory.js
lib/processMultipart.js
lib/tempFileHandler.js
lib/utilities.js
test/fileFactory.spec.js
test/multipartUploads.spec.js
test/server.js

Support empty files

---

lib/processNested.js
package-lock.json
package.json
test/processNested.spec.js

Fixes #236 
I'm going to fast track this to a release. Opened PR for record-keeping.
I also upgraded outdated packages (mocha + eslint) and ran an `audit fix`

Fix prototype pollution issue in `processNested`

---

example/README.md

Changed the example provided, I think it's clearer. I took these changes from the [server.js file](https://github.com/richardgirges/express-fileupload/blob/master/example/server.js).

Changed example

---

.gitignore
package-lock.json
package.json

Hi @richardgirges 
- Due to deprecation changed istanbul to nyc.
- Also updated deps.

Move from istanbul to nyc

---

lib/isEligibleRequest.js
test/isEligibleRequest.spec.js
test/utilities.spec.js

This PR is a successor of the PR #279 
But with some additional checks for methods and small refactoring.

Stricter request method and headers checks

---

package-lock.json
package.json

* Bump version to 1.4.2
* update dependencies.

Bump version to 1.4.2 & update dependencies
